enabled=true
key=0
radius=23.0
maximumSize=0.9
minimumSize=0.6
minimumSizeDistance=40.0
showDistance=false
showDistanceUnit=true
distanceTextSize=5.0
hideFarPointers=true
proximityGlow=false
glowDistance=15.0
glowEffect=Continuous
showBots=false
ignoreTeammates=true
hideInCrowds=true
hideBeyondDistance=40.0
colorMode=Team colors
fixedColor=White
distanceRedAt=6.0
distanceGreenAt=35.0
teammateColor=
